In [2]:
import numpy as np

In [3]:
py_list = [[2,4,6],[3,6,13],[5,8,9]]

In [4]:
np_ar = np.array(py_list)

In [6]:
np_ar

array([[ 2,  4,  6],
       [ 3,  6, 13],
       [ 5,  8,  9]])

In [7]:
np_ar.shape

(3, 3)

In [8]:
np_ar.size

9

In [9]:
np_ar.dtype

dtype('int32')

In [10]:
a = np.zeros((2,3))

In [11]:
a 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
x=np.arange(6)

In [15]:
x

array([0, 1, 2, 3, 4, 5])

In [16]:
x= np.linspace(2,5,5)

In [17]:
x

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [18]:
x=np.empty((2,2))

In [19]:
x

array([[2.12199579e-314, 0.00000000e+000],
       [6.42285340e-321, 4.22277163e-312]])

In [20]:
x = np.empty_like(a)

In [21]:
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
a =np.identity(10)

In [23]:
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np_ar.reshape(9,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 3],
       [ 6],
       [13],
       [ 5],
       [ 8],
       [ 9]])

In [25]:
np_ar.ravel()

array([ 2,  4,  6,  3,  6, 13,  5,  8,  9])

In [26]:
np_ar.T

array([[ 2,  3,  5],
       [ 4,  6,  8],
       [ 6, 13,  9]])

In [27]:
np_ar.sum()

56

In [28]:
np_ar.sum(axis=1)

array([12, 22, 22])

In [29]:
np_ar.flat

In [31]:
np_ar.ndim

2

In [32]:
np_ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [34]:
np_ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 2],
       [2, 2, 1]], dtype=int64)

In [36]:
ar2= np.array([[1,4,5],[8,7,3],[6,9,4]])

In [37]:
ar2

array([[1, 4, 5],
       [8, 7, 3],
       [6, 9, 4]])

In [38]:
ar2[2,2]=0

In [39]:
ar2

array([[1, 4, 5],
       [8, 7, 3],
       [6, 9, 0]])

In [40]:
np_ar+ar2

array([[ 3,  8, 11],
       [11, 13, 16],
       [11, 17,  9]])

In [41]:
np_ar*ar2

array([[ 2, 16, 30],
       [24, 42, 39],
       [30, 72,  0]])

In [42]:
np.where(ar2>7)

(array([1, 2], dtype=int64), array([0, 1], dtype=int64))

In [43]:
np.count_nonzero(ar2)

8